### ISSUE TITLE
Can not use Escape wile task switching

### ISSUE THREAD

**Issue by Ustice** [GoldenChaos/GoldenChaos-BTT#2] opened 2018-08-28 14:27 UTC
Not everyone knows this, but if you hold `⌘` after pressing `⌘+Tab`, you can go backwards by pressing back-tick, and cancel by pressing `Esc`. I do this a lot. Unfortunately, this is impossible with GoldenChaos-BTT installed. Even after enabling the `Esc` key, I have to hold the `fn` button to actually use `Esc`.

**Comment by GoldenChaos** [comment] 2018-11-07 11:41
This should actually be solved in the latest version. Sorry for not responding sooner - I usually keep support to the thread on the BTT forums! Please let me know if the latest version solved your issue 🙂

**Comment by iovis** [comment] 2019-08-12 22:04
Hi! I just started using GoldenChaos-BTT and I have this issue.
GoldenChaos-BTT 3.176 (Aug 9, 2019)

**Comment by GoldenChaos** [comment] 2019-08-13 16:32
I was able to reproduce the issue - I'll make sure it's fixed in the next version! Thanks for reporting :)

**Comment by GoldenChaos** [comment] 2019-09-14 19:36
Update on this: Unfortunately, it seems like macOS disables the Touch Bar app area (including all of BTT) while task switching at a system level. That means there's no way around this particular limitation unfortunately, unless Apple decides to change this behavior :( 

Closing this issue since it can't be implemented. If that ever changes, I'll make sure GC supports it.

**Closed by GoldenChaos** 2019-09-14 19:36 UTC
Labels: bug

**Comment by iovis** [comment] 2019-09-16 09:00
That's a shame, thanks for looking into this man
